server:
  port: 8003
mybatis:
  type-aliases-package: com.coder_tq.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.129.119.100:3306/db03?useUnicode=true&charatorEncoding=utf8&useSSL=false
    username: root
    password: Weiliangdada123`

#debug: true

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8003

info:
  author: coder_tq