server:
  port: 8001
mybatis:
  type-aliases-package: com.coder_tq.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.129.119.100:3306/db01?useUnicode=true&charatorEncoding=utf8&useSSL=false
    username: root
    password: Weiliangdada123`

#debug: true