server:
  port: 80
spring:
  application:
    name: springcloud-customer-dept

eureka:
  client:
    register-with-eureka: false #不在eureka中注册自己
    service-url:
      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka,http://eureka3:7003/eureka
